# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from admin.admin_order import Ui_adminPanelOrder
from admin.admin_shift import Ui_adminPanelShift
import bd
from admin.modal_staff import Ui_createStaff
import assets.resources

class Ui_adminPanelStaff(object):
    def setupUi(self, adminPanelStaff):
        self.main = adminPanelStaff
        adminPanelStaff.setObjectName("adminPanelStaff")
        adminPanelStaff.resize(972, 713)
        adminPanelStaff.setMinimumSize(QtCore.QSize(972, 713))
        adminPanelStaff.setMaximumSize(QtCore.QSize(1000, 800))
        self.frame = QtWidgets.QFrame(adminPanelStaff)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 991, 731))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.staffPageButton = QtWidgets.QPushButton(self.frame)
        self.staffPageButton.setGeometry(QtCore.QRect(10, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.staffPageButton.setFont(font)
        self.staffPageButton.setAutoFillBackground(False)
        self.staffPageButton.setStyleSheet("border: 1px solid rgb(153, 102, 51); \n"
"background-color: rgb(209, 207, 207);")
        self.staffPageButton.setAutoDefault(False)
        self.staffPageButton.setObjectName("staffPageButton")
        self.shiftPageButton = QtWidgets.QPushButton(self.frame)
        self.shiftPageButton.setGeometry(QtCore.QRect(260, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.shiftPageButton.setFont(font)
        self.shiftPageButton.setAutoFillBackground(False)
        self.shiftPageButton.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.shiftPageButton.setAutoDefault(False)
        self.shiftPageButton.setObjectName("shiftPageButton")
        self.shiftPageButton.clicked.connect(self.openShiftPanel)
        self.orderPageButton = QtWidgets.QPushButton(self.frame)
        self.orderPageButton.setGeometry(QtCore.QRect(510, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.orderPageButton.setFont(font)
        self.orderPageButton.setAutoFillBackground(False)
        self.orderPageButton.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.orderPageButton.setAutoDefault(False)
        self.orderPageButton.setObjectName("orderPageButton")
        self.orderPageButton.clicked.connect(self.openOrderPanel)
        self.createStaffButton = QtWidgets.QPushButton(self.frame)
        self.createStaffButton.setGeometry(QtCore.QRect(30, 80, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.createStaffButton.setFont(font)
        self.createStaffButton.setAutoFillBackground(False)
        self.createStaffButton.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.createStaffButton.setAutoDefault(False)
        self.createStaffButton.setObjectName("createStaffButton")
        self.createStaffButton.clicked.connect(self.addStaffModal)
        self.staffTable = QtWidgets.QTableWidget(self.frame)
        self.staffTable.setGeometry(QtCore.QRect(30, 140, 731, 531))
        self.staffTable.setAutoFillBackground(True)
        self.staffTable.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.staffTable.setRowCount(5)
        self.staffTable.setColumnCount(4)
        self.staffTable.setObjectName("staffTable")
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.staffTable.setHorizontalHeaderItem(3, item)
        self.staffTable.horizontalHeader().setVisible(True)
        self.staffTable.setAutoScroll( True)
        self.staffTable.itemClicked.connect(self.tableStaffEditing)
        self.staffTable.horizontalHeader().setCascadingSectionResizes(False)
        self.icon = QtWidgets.QLabel(self.frame)
        self.icon.setGeometry(QtCore.QRect(790, 30, 161, 191))
        self.icon.setText("")
        self.icon.setTextFormat(QtCore.Qt.RichText)
        self.icon.setPixmap(QtGui.QPixmap(":assets/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.saveStaff = QtWidgets.QPushButton(self.frame)
        self.saveStaff.setGeometry(QtCore.QRect(790, 630, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.saveStaff.setFont(font)
        self.saveStaff.setAutoFillBackground(False)
        self.saveStaff.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.saveStaff.setAutoDefault(False)
        self.saveStaff.setObjectName("saveStaff")
        self.saveStaff.setVisible(False)
        self.saveStaff.clicked.connect(self.saveEditStaff)

        self.retranslateUi(adminPanelStaff)
        QtCore.QMetaObject.connectSlotsByName(adminPanelStaff)

    def retranslateUi(self, adminPanelStaff):
        _translate = QtCore.QCoreApplication.translate
        adminPanelStaff.setWindowTitle(_translate("adminPanelStaff", "Панель администратора. Сотрудники"))
        self.staffPageButton.setText(_translate("adminPanelStaff", "Сотрудники"))
        self.shiftPageButton.setText(_translate("adminPanelStaff", "Смены"))
        self.orderPageButton.setText(_translate("adminPanelStaff", "Заказы"))
        self.createStaffButton.setText(_translate("adminPanelStaff", "Создать сотрудника"))
        self.staffTable.setSortingEnabled(False)
        item = self.staffTable.horizontalHeaderItem(0)
        item.setText(_translate("adminPanelStaff", "id"))
        item = self.staffTable.horizontalHeaderItem(1)
        item.setText(_translate("adminPanelStaff", "ФИО"))
        item = self.staffTable.horizontalHeaderItem(2)
        item.setText(_translate("adminPanelStaff", "Роль"))
        item = self.staffTable.horizontalHeaderItem(3)
        item.setText(_translate("adminPanelStaff", "Статус"))
        self.saveStaff.setText(_translate("adminPanelStaff", "Сохранить"))

    def tableStaffEditing(self):
        self.saveStaff.setVisible(True)

    def loadStaffTable(self):
        connection = bd.connectBd()
        cursor = connection.cursor()
        cursor.execute("SELECT staff.staff_id,staff.staff_fam, staff.staff_name,Staff_role.name,Staff_status.name, work_shift.date from staff join Staff_role on staff.role = Staff_role.role_id LEFT JOIN Staff_status on staff.status=Staff_status.status_id join work_shift on staff.work_shift=work_shift.shift_id;")
        data_staff = cursor.fetchall()
        self.staffTable.setRowCount(0)
        self.staffTable.setColumnCount(6)
        self.staffTable.hideColumn(0)
        for row_number, row_data in enumerate(data_staff):
            self.staffTable.insertRow(row_number)
            for c_number, data in enumerate(row_data):
                self.staffTable.setItem(
                    row_number,
                    c_number,
                    QtWidgets.QTableWidgetItem(str(row_data[data])),
                )
        self.staffTable.setHorizontalHeaderLabels(
           ["id", "Фамилия","Имя", "Роль", "Статус","Дата смены"]
        )
        self.staffTable.resizeColumnsToContents()
        connection.close()

    def saveEditStaff(self):
        connection = bd.connectBd()
        cursor = connection.cursor()
        for i in range(self.staffTable.rowCount()):
            id = self.staffTable.item(i, 0).text()
            fam = self.staffTable.item(i, 1).text()
            name = self.staffTable.item(i, 2).text()
            role = self.staffTable.item(i, 3).text()
            status = self.staffTable.item(i, 4).text()
            date = self.staffTable.item(i, 5).text()
            cursor.execute(
                "UPDATE Staff SET staff_fam = '{}', staff_name ='{}', work_shift = (SELECT work_shift.shift_id FROM work_shift WHERE work_shift.date = '{}'), status = (SELECT Staff_status.status_id FROM Staff_status WHERE Staff_status.name = '{}'), role = (SELECT Staff_role.role_id FROM Staff_role WHERE Staff_role.name = '{}') WHERE staff_id = {} ;".format(fam, name,date,status,role,id)
            )
        connection.commit()
        cursor.execute("SELECT staff.staff_id,staff.staff_fam, staff.staff_name,Staff_role.name,Staff_status.name, work_shift.date from staff join Staff_role on staff.role = Staff_role.role_id LEFT JOIN Staff_status on staff.status=Staff_status.status_id join work_shift on staff.work_shift=work_shift.shift_id;")
        data_staff = cursor.fetchall()
        self.staffTable.setRowCount(0)
        self.staffTable.setColumnCount(6)
        self.staffTable.hideColumn(0)
        for row_number, row_data in enumerate(data_staff):
            self.staffTable.insertRow(row_number)
            for c_number, data in enumerate(row_data):
                self.staffTable.setItem(
                    row_number,
                    c_number,
                    QtWidgets.QTableWidgetItem(str(row_data[data])),
                )
        self.staffTable.setHorizontalHeaderLabels(
            ["id", "Фамилия","Имя", "Роль", "Статус","Дата смены"]
        )
        self.staffTable.resizeColumnsToContents()
        connection.close()
        self.saveStaff.setVisible(False)

    def addStaffModal(self):
        self.staff_modal = QWidget()
        self.ui = Ui_createStaff()
        self.ui.setupUi(self.staff_modal)
        self.ui.saveStaffModalButton.clicked.connect(self.loadStaffTable)
        self.staff_modal.show()

    def openShiftPanel(self):
        self.shift = QWidget()
        self.ui_shift = Ui_adminPanelShift()
        self.ui_shift.setupUi(self.shift)
        self.ui_shift.loadShifttaffTable()
        self.ui_shift.admin_panel = self.main
        self.shift.show()
        self.ui_shift.staffPageButton.clicked.connect(self.main.show)
        self.main.close()

    def openOrderPanel(self):
        self.order = QWidget()
        self.ui_order = Ui_adminPanelOrder()
        self.ui_order.setupUi(self.order)
        self.ui_order.loadOredersTable()
        self.order.show()
        self.ui_order.staffPageButton.clicked.connect(self.main.show)
        self.ui_order.shiftPageButton.clicked.connect(self.openShiftPanel)
        self.main.close()

