# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modal_staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bd

class Ui_createStaff(object):
    def setupUi(self, createStaff):
        self.main = createStaff
        createStaff.setObjectName("createStaff")
        createStaff.resize(971, 713)
        self.modalStaff = QtWidgets.QFrame(createStaff)
        self.modalStaff.setGeometry(QtCore.QRect(-10, -10, 991, 731))
        self.modalStaff.setAutoFillBackground(True)
        self.modalStaff.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modalStaff.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modalStaff.setObjectName("modalStaff")
        self.famInput = QtWidgets.QLineEdit(self.modalStaff)
        self.famInput.setGeometry(QtCore.QRect(130, 450, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.famInput.setFont(font)
        self.famInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.famInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.famInput.setText("")
        self.famInput.setObjectName("famInput")
        self.otchInput = QtWidgets.QLineEdit(self.modalStaff)
        self.otchInput.setGeometry(QtCore.QRect(130, 530, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.otchInput.setFont(font)
        self.otchInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.otchInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.otchInput.setText("")
        self.otchInput.setObjectName("otchInput")
        self.nameInput = QtWidgets.QLineEdit(self.modalStaff)
        self.nameInput.setGeometry(QtCore.QRect(560, 450, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.nameInput.setFont(font)
        self.nameInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.nameInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.nameInput.setText("")
        self.nameInput.setObjectName("nameInput")
        self.icon = QtWidgets.QLabel(self.modalStaff)
        self.icon.setGeometry(QtCore.QRect(370, 60, 251, 291))
        self.icon.setText("")
        self.icon.setTextFormat(QtCore.Qt.RichText)
        self.icon.setPixmap(QtGui.QPixmap(":assets/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.saveStaffModalButton = QtWidgets.QPushButton(self.modalStaff)
        self.saveStaffModalButton.setGeometry(QtCore.QRect(130, 620, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.saveStaffModalButton.setFont(font)
        self.saveStaffModalButton.setAutoFillBackground(False)
        self.saveStaffModalButton.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.saveStaffModalButton.setAutoDefault(False)
        self.saveStaffModalButton.setObjectName("saveStaffModalButton")
        self.saveStaffModalButton.clicked.connect(self.saveStaff)
        self.cancelStaffModalButton = QtWidgets.QPushButton(self.modalStaff)
        self.cancelStaffModalButton.setGeometry(QtCore.QRect(560, 620, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.cancelStaffModalButton.setFont(font)
        self.cancelStaffModalButton.setAutoFillBackground(False)
        self.cancelStaffModalButton.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.cancelStaffModalButton.setAutoDefault(False)
        self.cancelStaffModalButton.setObjectName("cancelStaffModalButton")
        self.cancelStaffModalButton.clicked.connect(createStaff.close)
        self.chooseRole = QtWidgets.QComboBox(self.modalStaff)
        self.chooseRole.setGeometry(QtCore.QRect(560, 530, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.chooseRole.setFont(font)
        self.chooseRole.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.chooseRole.setEditable(True)
        self.chooseRole.setIconSize(QtCore.QSize(20, 20))
        self.chooseRole.setObjectName("chooseRole")
        self.chooseRole.addItem("")
        self.chooseRole.addItem("")

        self.retranslateUi(createStaff)
        self.chooseRole.setCurrentIndex(-1)
        self.cancelStaffModalButton.clicked.connect(createStaff.close) # type: ignore
        self.saveStaffModalButton.clicked.connect(createStaff.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(createStaff)

    def retranslateUi(self, createStaff):
        _translate = QtCore.QCoreApplication.translate
        createStaff.setWindowTitle(_translate("createStaff", "Создание сотрудника"))
        self.famInput.setPlaceholderText(_translate("createStaff", "Введите фамилию"))
        self.otchInput.setPlaceholderText(_translate("createStaff", "Введите отчество"))
        self.nameInput.setPlaceholderText(_translate("createStaff", "Введите имя"))
        self.saveStaffModalButton.setText(_translate("createStaff", "Сохранить"))
        self.cancelStaffModalButton.setText(_translate("createStaff", "Отмена"))
        self.chooseRole.setCurrentText(_translate("createStaff", "Выберете роль"))
        self.chooseRole.setItemText(0, _translate("createStaff", "Повар"))
        self.chooseRole.setItemText(1, _translate("createStaff", "Официант"))

    def saveStaff(self):
        connection = bd.connectBd()
        cursor = connection.cursor()
        fam = self.famInput.text()
        print(fam)
        name = self.nameInput.text()
        print(name)
        otch = self.otchInput.text()
        print(otch)
        role = self.chooseRole.itemText(self.chooseRole.currentIndex())
        print(role)
        cursor.execute("INSERT INTO Staff (staff_id, staff_fam, staff_name, staff_otch, role, status, work_shift, login, password) VALUES (NULL, '{}', '{}', '{}', (SELECT Staff_role.role_id FROM Staff_role WHERE Staff_role.name = '{}'), '1', '1', NULL, NULL);".format(fam,name,otch,role))
        connection.commit()
        connection.close()
        self.main.close
        

