# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staff_in_shift.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bd


class Ui_StaffInShift(object):
    def setupUi(self, StaffInShift):
        StaffInShift.setObjectName("StaffInShift")
        StaffInShift.resize(971, 713)
        self.frame = QtWidgets.QFrame(StaffInShift)
        self.frame.setGeometry(QtCore.QRect(0, 0, 991, 731))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.shiftTable = QtWidgets.QTableWidget(self.frame)
        self.shiftTable.setGeometry(QtCore.QRect(30, 140, 731, 531))
        self.shiftTable.setAutoFillBackground(True)
        self.shiftTable.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.shiftTable.setRowCount(5)
        self.shiftTable.setColumnCount(4)
        self.shiftTable.setObjectName("shiftTable")
        item = QtWidgets.QTableWidgetItem()
        self.shiftTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shiftTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shiftTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.shiftTable.setHorizontalHeaderItem(3, item)
        self.shiftTable.horizontalHeader().setVisible(True)
        self.shiftTable.horizontalHeader().setCascadingSectionResizes(False)
        self.icon = QtWidgets.QLabel(self.frame)
        self.icon.setGeometry(QtCore.QRect(790, 30, 161, 191))
        self.icon.setText("")
        self.icon.setTextFormat(QtCore.Qt.RichText)
        self.icon.setPixmap(QtGui.QPixmap(":assets/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")

        self.idShift = QtWidgets.QPushButton(self.frame)
        self.idShift.setGeometry(QtCore.QRect(780, 580, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.idShift.setFont(font)
        self.idShift.setAutoFillBackground(False)
        self.idShift.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.idShift.setAutoDefault(False)
        self.idShift.setObjectName("saveShift")
        self.idShift.setVisible(False)

        self.staffOfShift = QtWidgets.QLabel(self.frame)
        self.staffOfShift.setGeometry(QtCore.QRect(400, 20, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.staffOfShift.setFont(font)
        self.staffOfShift.setObjectName("staffOfShift")
        self.closeStaffInShift = QtWidgets.QPushButton(self.frame)
        self.closeStaffInShift.setGeometry(QtCore.QRect(780, 630, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.closeStaffInShift.setFont(font)
        self.closeStaffInShift.setAutoFillBackground(False)
        self.closeStaffInShift.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.closeStaffInShift.setAutoDefault(False)
        self.closeStaffInShift.setObjectName("closeStaffInShift")

        self.retranslateUi(StaffInShift)
        self.closeStaffInShift.clicked.connect(StaffInShift.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StaffInShift)

    def retranslateUi(self, StaffInShift):
        _translate = QtCore.QCoreApplication.translate
        StaffInShift.setWindowTitle(_translate("StaffInShift", "Состав смены"))
        self.shiftTable.setSortingEnabled(False)
        item = self.shiftTable.horizontalHeaderItem(0)
        item.setText(_translate("StaffInShift", "id"))
        item = self.shiftTable.horizontalHeaderItem(1)
        item.setText(_translate("StaffInShift", "Дата"))
        item = self.shiftTable.horizontalHeaderItem(2)
        item.setText(_translate("StaffInShift", "Начало"))
        item = self.shiftTable.horizontalHeaderItem(3)
        item.setText(_translate("StaffInShift", "Конец"))
        self.staffOfShift.setText(_translate("StaffInShift", "Сотрудники смены"))
        self.closeStaffInShift.setText(_translate("StaffInShift", "Назад к сменам"))
    
    def loadStaffInShift(self):
        id = self.idShift.text()
        connection = bd.connectBd()
        cursor = connection.cursor()
        cursor.execute("SELECT staff.staff_id,staff.staff_fam, staff.staff_name,Staff_role.name,Staff_status.name, work_shift.date from staff join Staff_role on staff.role = Staff_role.role_id LEFT JOIN Staff_status on staff.status=Staff_status.status_id join work_shift on staff.work_shift=work_shift.shift_id WHERE work_shift = '{}';".format(id))
        data_staff = cursor.fetchall()
        self.shiftTable.setRowCount(0)
        self.shiftTable.setColumnCount(6)
        self.shiftTable.hideColumn(0)
        for row_number, row_data in enumerate(data_staff):
            self.shiftTable.insertRow(row_number)
            for c_number, data in enumerate(row_data):
                self.shiftTable.setItem(
                    row_number,
                    c_number,
                    QtWidgets.QTableWidgetItem(str(row_data[data])),
                )
        self.shiftTable.setHorizontalHeaderLabels(
           ["id", "Фамилия","Имя", "Роль", "Статус","Дата смены"]
        )
        self.shiftTable.resizeColumnsToContents()
        connection.close()

