# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_order_ofic.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bd


class Ui_createOrderModal(object):
    def setupUi(self, createOrderModal):
        self.main = createOrderModal
        createOrderModal.setObjectName("createOrderModal")
        createOrderModal.resize(971, 713)
        self.frame = QtWidgets.QFrame(createOrderModal)
        self.frame.setGeometry(QtCore.QRect(0, -10, 991, 731))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.orderDescInput = QtWidgets.QLineEdit(self.frame)
        self.orderDescInput.setGeometry(QtCore.QRect(130, 450, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.orderDescInput.setFont(font)
        self.orderDescInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.orderDescInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.orderDescInput.setText("")
        self.orderDescInput.setObjectName("orderDescInput")
        self.numbCustomerInput = QtWidgets.QLineEdit(self.frame)
        self.numbCustomerInput.setGeometry(QtCore.QRect(360, 530, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.numbCustomerInput.setFont(font)
        self.numbCustomerInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.numbCustomerInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.numbCustomerInput.setText("")
        self.numbCustomerInput.setObjectName("numbCustomerInput")
        self.numbTableInput = QtWidgets.QLineEdit(self.frame)
        self.numbTableInput.setGeometry(QtCore.QRect(560, 450, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.numbTableInput.setFont(font)
        self.numbTableInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.numbTableInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.numbTableInput.setText("")
        self.numbTableInput.setObjectName("numbTableInput")
        self.icon = QtWidgets.QLabel(self.frame)
        self.icon.setGeometry(QtCore.QRect(370, 60, 251, 291))
        self.icon.setText("")
        self.icon.setTextFormat(QtCore.Qt.RichText)
        self.icon.setPixmap(QtGui.QPixmap(":assets/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.saveOrderModalButton = QtWidgets.QPushButton(self.frame)
        self.saveOrderModalButton.setGeometry(QtCore.QRect(130, 620, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.saveOrderModalButton.setFont(font)
        self.saveOrderModalButton.setAutoFillBackground(False)
        self.saveOrderModalButton.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.saveOrderModalButton.setAutoDefault(False)
        self.saveOrderModalButton.setObjectName("saveOrderModalButton")
        self.cancelOrderModalButton = QtWidgets.QPushButton(self.frame)
        self.cancelOrderModalButton.setGeometry(QtCore.QRect(560, 620, 291, 41))
        self.saveOrderModalButton.clicked.connect(self.addNewOrder)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.cancelOrderModalButton.setFont(font)
        self.cancelOrderModalButton.setAutoFillBackground(False)
        self.cancelOrderModalButton.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.cancelOrderModalButton.setAutoDefault(False)
        self.cancelOrderModalButton.setObjectName("cancelOrderModalButton")

        self.retranslateUi(createOrderModal)
        self.saveOrderModalButton.clicked.connect(createOrderModal.close) # type: ignore
        self.cancelOrderModalButton.clicked.connect(createOrderModal.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(createOrderModal)

    def retranslateUi(self, createOrderModal):
        _translate = QtCore.QCoreApplication.translate
        createOrderModal.setWindowTitle(_translate("createOrderModal", "Создание заказа"))
        self.orderDescInput.setPlaceholderText(_translate("createOrderModal", "Введите блюда и напитки"))
        self.numbCustomerInput.setPlaceholderText(_translate("createOrderModal", "Введите кол-во гостей"))
        self.numbTableInput.setPlaceholderText(_translate("createOrderModal", "Введите номер столика"))
        self.saveOrderModalButton.setText(_translate("createOrderModal", "Сохранить"))
        self.cancelOrderModalButton.setText(_translate("createOrderModal", "Отмена"))
    
    def addNewOrder(self):
        desc = self.orderDescInput.text()
        number_table = self.numbTableInput.text()
        number_cust = self.numbCustomerInput.text()
        connection = bd.connectBd()
        cursor = connection.cursor()
        cursor.execute("INSERT INTO `Orders` (`order_id`, `description`, `table_number`, `count_customer`, `status_kitchen`, `status_waiter`) VALUES (NULL, '{}', '{}', '{}', '3', '1');".format(desc, number_table, number_cust))
        connection.commit()
        connection.close()
        self.main.close



