# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ofic_order.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

import bd
from waiter.create_order_ofic import Ui_createOrderModal

class Ui_oficOrders(object):
    def setupUi(self, oficOrders):
        oficOrders.setObjectName("oficOrders")
        oficOrders.resize(971, 713)
        self.frame = QtWidgets.QFrame(oficOrders)
        self.frame.setGeometry(QtCore.QRect(-10, -10, 991, 731))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.orderPageButton = QtWidgets.QPushButton(self.frame)
        self.orderPageButton.setGeometry(QtCore.QRect(10, 10, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.orderPageButton.setFont(font)
        self.orderPageButton.setAutoFillBackground(False)
        self.orderPageButton.setStyleSheet("border: 1px solid rgb(153, 102, 51);\n"
"background-color: rgb(209, 207, 207);")
        self.orderPageButton.setAutoDefault(False)
        self.orderPageButton.setObjectName("orderPageButton")
        self.orderTable = QtWidgets.QTableWidget(self.frame)
        self.orderTable.setGeometry(QtCore.QRect(30, 140, 731, 531))
        self.orderTable.setAutoFillBackground(True)
        self.orderTable.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.orderTable.setRowCount(5)
        self.orderTable.setColumnCount(4)
        self.orderTable.setObjectName("orderTable")
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(3, item)
        self.orderTable.horizontalHeader().setVisible(True)
        self.orderTable.itemClicked.connect(self.showSaveOrder)
        self.orderTable.horizontalHeader().setCascadingSectionResizes(False)
        self.icon = QtWidgets.QLabel(self.frame)
        self.icon.setGeometry(QtCore.QRect(790, 30, 161, 191))
        self.icon.setText("")
        self.icon.setTextFormat(QtCore.Qt.RichText)
        self.icon.setPixmap(QtGui.QPixmap(":/assets/:assets/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.createOrderButton = QtWidgets.QPushButton(self.frame)
        self.createOrderButton.setGeometry(QtCore.QRect(30, 70, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.createOrderButton.setFont(font)
        self.createOrderButton.setAutoFillBackground(False)
        self.createOrderButton.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.createOrderButton.setAutoDefault(False)
        self.createOrderButton.setObjectName("createOrderButton")
        self.saveOrder = QtWidgets.QPushButton(self.frame)
        self.saveOrder.setGeometry(QtCore.QRect(790, 630, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.saveOrder.setFont(font)
        self.saveOrder.setAutoFillBackground(False)
        self.saveOrder.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.saveOrder.setAutoDefault(False)
        self.saveOrder.setObjectName("saveOrder")
        self.saveOrder.setVisible(False)
        self.saveOrder.clicked.connect(self.updateOrderStatus)
        self.createOrderButton.clicked.connect(self.addOrderModalShow)

        self.retranslateUi(oficOrders)
        QtCore.QMetaObject.connectSlotsByName(oficOrders)

    def retranslateUi(self, oficOrders):
        _translate = QtCore.QCoreApplication.translate
        oficOrders.setWindowTitle(_translate("oficOrders", "Панель официанта. Заказы"))
        self.orderPageButton.setText(_translate("oficOrders", "Заказы"))
        self.orderTable.setSortingEnabled(False)
        item = self.orderTable.horizontalHeaderItem(0)
        item.setText(_translate("oficOrders", "id"))
        item = self.orderTable.horizontalHeaderItem(1)
        item.setText(_translate("oficOrders", "Заказ"))
        item = self.orderTable.horizontalHeaderItem(2)
        item.setText(_translate("oficOrders", "Статус зала"))
        item = self.orderTable.horizontalHeaderItem(3)
        item.setText(_translate("oficOrders", "Статус кухни"))
        self.createOrderButton.setText(_translate("oficOrders", "Создать заказ"))
        self.saveOrder.setText(_translate("oficOrders", "Сохранить"))

    def showSaveOrder(self):
         self.saveOrder.setVisible(True)

    def loadOrder(self):
        connection = bd.connectBd()
        cursor = connection.cursor()
        cursor.execute("SELECT  Orders.order_id,Orders.description,Orders.table_number,Orders.count_customer,Status_order_waiter.name,Status_order_kitchen.name FROM `Orders` join Status_order_waiter on Orders.status_waiter=Status_order_waiter.status_waiter_id left join Status_order_kitchen on Orders.status_kitchen=Status_order_kitchen.status_kitchen_id;")
        data_staff = cursor.fetchall()
        self.orderTable.setRowCount(0)
        self.orderTable.setColumnCount(6)
        self.orderTable.hideColumn(0)
        for row_number, row_data in enumerate(data_staff):
            self.orderTable.insertRow(row_number)
            for c_number, data in enumerate(row_data):
                self.orderTable.setItem(
                    row_number,
                    c_number,
                    QtWidgets.QTableWidgetItem(str(row_data[data])),
                )
        self.orderTable.setHorizontalHeaderLabels(
           ["id", "Описание заказа","Номер столика", "Кол-во гостей", "Статус зала", "Статус кухни"]
        )
        self.orderTable.resizeColumnsToContents()
        connection.close()

    def addOrderModalShow(self):
            self.modal = QWidget()
            self.ui = Ui_createOrderModal()
            self.ui.setupUi(self.modal)
            self.modal.show()
            self.ui.saveOrderModalButton.clicked.connect(self.loadOrder)

    def updateOrderStatus(self):
        connection = bd.connectBd()
        cursor = connection.cursor()
        for i in range(self.orderTable.rowCount()):
            id = self.orderTable.item(i, 0).text()
            status_waiter = self.orderTable.item(i, 4).text()
            cursor.execute(
                "UPDATE `Orders` SET `status_waiter` = (SELECT status_waiter_id FROM Status_order_waiter WHERE name = '{}') WHERE `Orders`.`order_id` = {};".format(status_waiter,id)
            )
        connection.commit()
        cursor.execute("SELECT  Orders.order_id,Orders.description,Orders.table_number,Orders.count_customer,Status_order_waiter.name,Status_order_kitchen.name FROM `Orders` join Status_order_waiter on Orders.status_waiter=Status_order_waiter.status_waiter_id left join Status_order_kitchen on Orders.status_kitchen=Status_order_kitchen.status_kitchen_id;")
        data_order = cursor.fetchall()
        self.orderTable.setRowCount(0)
        self.orderTable.setColumnCount(6)
        self.orderTable.hideColumn(0)
        for row_number, row_data in enumerate(data_order):
            self.orderTable.insertRow(row_number)
            for c_number, data in enumerate(row_data):
                self.orderTable.setItem(
                    row_number,
                    c_number,
                    QtWidgets.QTableWidgetItem(str(row_data[data])),
                )
        self.orderTable.setHorizontalHeaderLabels(
           ["id", "Описание заказа","Номер столика", "Кол-во гостей", "Статус зала", "Статус кухни"]
        )
        self.orderTable.resizeColumnsToContents()
        connection.close()
        self.saveOrder.setVisible(False)


