# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import bd
from admin.admin_staff import Ui_adminPanelStaff
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

from kitchen.kitchen_order import Ui_kitchenPanel
from waiter.ofic_order import Ui_oficOrders
import assets.resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(968, 713)
        MainWindow.setMinimumSize(QtCore.QSize(968, 713))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        MainWindow.setBaseSize(QtCore.QSize(968, 713))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(968, 713))
        self.centralwidget.setMaximumSize(QtCore.QSize(968, 713))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-10, -10, 1000, 731))
        self.background.setMinimumSize(QtCore.QSize(981, 731))
        self.background.setMaximumSize(QtCore.QSize(1000, 799))
        self.background.setBaseSize(QtCore.QSize(981, 731))
        self.background.setAutoFillBackground(True)
        self.background.setStyleSheet("")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        label = QLabel(self.background)
        pixmap = QtGui.QPixmap(":assets/icon.png")
        if pixmap.isNull():
            print("Error loading image:")
        label.setGeometry(QtCore.QRect(380, 60, 251, 291))
        label.setPixmap(pixmap)
        label.setScaledContents(True)
        self.welcomeText = QtWidgets.QLabel(self.background)
        self.welcomeText.setGeometry(QtCore.QRect(390, 370, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(16)
        self.welcomeText.setFont(font)
        self.welcomeText.setTextFormat(QtCore.Qt.AutoText)
        self.welcomeText.setObjectName("welcomeText")
        self.errorLoginText = QtWidgets.QLabel(self.background)
        self.errorLoginText.setGeometry(QtCore.QRect(360, 400, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(8)
        self.errorLoginText.setFont(font)
        self.errorLoginText.setTextFormat(QtCore.Qt.AutoText)
        self.errorLoginText.setObjectName("errorLoginText")
        self.errorLoginText.setVisible(False)

        self.checkText = QtWidgets.QLabel(self.background)
        self.checkText.setGeometry(QtCore.QRect(360, 400, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(8)
        self.checkText.setFont(font)
        self.checkText.setTextFormat(QtCore.Qt.AutoText)
        self.checkText.setObjectName("checkText")
        self.checkText.setVisible(False)

        self.loginInput = QtWidgets.QLineEdit(self.background)
        self.loginInput.setGeometry(QtCore.QRect(360, 440, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.loginInput.setFont(font)
        self.loginInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.loginInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.loginInput.setText("")
        self.loginInput.setObjectName("loginInput")
        self.loginInput.textEdited.connect(self.loginEntering)

        self.passwordErrorText = QtWidgets.QLabel(self.background)
        self.passwordErrorText.setGeometry(QtCore.QRect(360, 470, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(8)
        self.passwordErrorText.setFont(font)
        self.passwordErrorText.setTextFormat(QtCore.Qt.AutoText)
        self.passwordErrorText.setObjectName("passwordErrorText")
        self.passwordErrorText.setVisible(False)

        self.passwordInput = QtWidgets.QLineEdit(self.background)
        self.passwordInput.setGeometry(QtCore.QRect(360, 510, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("border: 1px solid rgb(153, 102, 51);")
        self.passwordInput.setText("")
        self.passwordInput.setObjectName("passwordInput")
        self.passwordInput.textEdited.connect(self.passwordEntering)
        self.enterButton = QtWidgets.QPushButton(self.background)
        self.enterButton.setGeometry(QtCore.QRect(360, 580, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(14)
        self.enterButton.setFont(font)
        self.enterButton.setAutoFillBackground(False)
        self.enterButton.setStyleSheet("background-color: rgb(153, 102, 51);")
        self.enterButton.setAutoDefault(False)
        self.enterButton.setObjectName("enterButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.enterButton.clicked.connect(self.enterClick) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация в систему кафе \"Сезон\""))
        self.welcomeText.setText(_translate("MainWindow", "Добро пожаловать!"))
        self.loginInput.setPlaceholderText(_translate("MainWindow", "Введите логин"))
        self.passwordInput.setPlaceholderText(_translate("MainWindow", "Введите пароль"))
        self.enterButton.setText(_translate("MainWindow", "Войти"))
        self.errorLoginText.setText(_translate("MainWindow", "Неверный логин. Попробуйте снова"))
        self.passwordErrorText.setText(_translate("MainWindow", "Неверный пароль. Попробуйте снова"))
    
    def loginEntering(self):
        self.errorLoginText.setVisible(False)
    def passwordEntering(self):
        self.passwordErrorText.setVisible(False)

    def admin_staff_panel(self):
        self.staff = QWidget()
        self.ui = Ui_adminPanelStaff()
        self.ui.setupUi(self.staff)
        self.ui.loadStaffTable()
        self.staff.show()

    def waiter_panel(self):
        self.waiter = QWidget()
        self.ui = Ui_oficOrders()
        self.ui.setupUi(self.waiter)
        self.ui.loadOrder()
        self.waiter.show()

    def kitchen_panel(self):
        self.kitchen = QWidget()
        self.ui = Ui_kitchenPanel()
        self.ui.setupUi(self.kitchen)
        self.ui.loadOrder()
        self.kitchen.show()


    def enterClick(self):
        connection = bd.connectBd()
        cursor = connection.cursor()
        login = self.loginInput.text()
        password = self.passwordInput.text()
        cursor.execute(f"SELECT role FROM Staff WHERE login='{login}';")
        rowsLogin = cursor.fetchall()
        print(len(rowsLogin))
        if len(rowsLogin) == 0:
            self.loginInput.setText('')
            self.passwordInput.setText('')
            self.errorLoginText.setVisible(True)
        cursor.execute(f"SELECT role FROM Staff WHERE password='{password}' AND login='{login}';")
        rowsPassword = cursor.fetchall()
        if len(rowsPassword) == 0:
            self.passwordInput.setText('')
            self.passwordErrorText.setVisible(True)
            self.checkText.setVisible(False)
        if len(rowsPassword) != 0:
            if rowsPassword[0]['role'] == 3:
                self.admin_staff_panel()
                self.checkText.setVisible(True)
                self.MainWindow.close() 
            if rowsPassword[0]['role']== 1:
                self.kitchen_panel()
                self.checkText.setVisible(True)
                self.MainWindow.close() 
            if rowsPassword[0]['role'] == 2:
                self.waiter_panel()
                self.checkText.setVisible(True)
                self.MainWindow.close() 
        connection.close()
            
        


    
